networks:
  monitoring:
    external: true
    name: monitoring
  production:
    external: true
    name: production

services:
  satis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satis
    restart: unless-stopped
    volumes:
      - ./config/satis.json:/var/satis/config/satis.json:ro
      - ./output:/var/satis/output
      - satis-composer-cache:/root/.composer/cache
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.satis.rule=Host(`packages.upsolve.com.br`)"
      - "traefik.http.routers.satis.entrypoints=websecure"
      - "traefik.http.routers.satis.tls.certresolver=letsencrypt"
      - "traefik.http.services.satis.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.satis-auth.basicauth.users=${SATIS_BASIC_AUTH}"
      - "traefik.http.routers.satis.middlewares=satis-auth"
      - "traefik.docker.network=production"
    networks:
      monitoring:
        external: true
        name: monitoring
      production:
        external: true
        name: production

volumes:
  satis-composer-cache: