networks:
  monitoring:
    external: true
    name: monitoring
  production:
    external: true
    name: production

services:  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      # Habilita descoberta do container
      - "traefik.enable=true"
      # Habilita a rota do traefik
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.upsolve.com.br`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      # Habilita o service do traefik (Exposer a porta interna do prometheus)
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      # Habilita o middleware de segurança
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=admin:$$2y$$05$$BNzlP8aEzvem1GTzFo3g2e9yQSx.lDaVsB8dKSjA2NjDcGInznFkG"
      - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
      - "traefik.docker.network=production"
    networks:
      - monitoring
      - production



    