networks:
  monitoring:
    external: true
    name: monitoring

services:
  node_exporter:
    image: prom/node-exporter:v1.12.0
    container_name: node_exporter
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    cpus: "0.25"
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    networks:
      - monitoring
